### PR TITLE
Rebased with master.

### PR DESCRIPTION
**Pull request by sumith1896**
Let me know if this is fine. I'll then send the cleaning up commits.
Resolved merge conflicts. I don't know if this is the right way to do this or I should send a PR with updated branch from my repo. Either ways let me know
cc @certik @shivamvats

### CODE REVIEW

**Comment by certik** [comment]
This doesn't seem like a clean rebase. Just rebase your commits on top of
the latest master. Also it seems you sent it against a wrong repository.

**Comment by sumith1896** [comment]
The PR to this repo was intentional so as to update the PR @shivamvats had sent there.
Are you suggesting to send a fresh PR directly to SymEngine from the updated master with @shivamvats as well as my changes?

**Comment by sumith1896** [comment]
I can rebase his commits on top of master and put mine there too and then send a PR to SymEngine. Would that be better?

**Comment by certik** [comment]
From my phone it's hard to figure out what the PR is doing, as it shows
some patches that were already merged with master. I will need to use a
computer.

**Comment by sumith1896** [comment]
Cleaner PR here https://github.com/sympy/symengine/pull/454. I think this is the way to go forward. Closing this. Sorry for the inconvenience.

**Pull request closed without merging**
